from domain.models import Manga, Volume, VolumeInfo

class BaseAPI:
    def get_manga(self) -> Manga: ...
    def get_volumes_info(self) -> list[VolumeInfo]: ...
    def get_volumes(self) -> list[Volume]: ...
